-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: cf550fcab3f12015f8676b8278b30e1a5bc10e70
    hooks:
    -   id: trailing-whitespace
        language_version: python2.7
    -   id: end-of-file-fixer
        language_version: python2.7
    -   id: autopep8-wrapper
        language_version: python2.7
    -   id: check-docstring-first
        language_version: python2.7
    -   id: check-json
        language_version: python2.7
    -   id: check-yaml
        # Exclude fsm cookiecutter files
        files: ^(?!.*template).*\.(yaml|yml|eyaml)$
        language_version: python2.7
    -   id: debug-statements
        language_version: python2.7
    -   id: name-tests-test
        args: [--django]
        files: ^tests/.*\.py$
        language_version: python2.7
    -   id: requirements-txt-fixer
        language_version: python2.7
    -   id: flake8
        exclude: ^docs/source/conf.py$
        language_version: python2.7
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
