version: '3'
networks:
  kubeadm-dind-net:
    external: True
volumes:
  ssh-data: {}
  nail-etc:
services:
  itest_xenial:
    build: ../yelp_package/dockerfiles/xenial/
  paasta_master:
    build:
      context: ../
      dockerfile: ./yelp_package/dockerfiles/playground/Dockerfile
    volumes:
      - ../:/work:rw
      - ./paasta:/etc/paasta:rw
      - ./docker_registry_kube.json:/etc/paasta/docker_registry.json:rw
      - ./boto:/etc/boto:rw
      - ./example-services-k8s:/nail/etc/services:rw
      - ./kubernetes:/etc/kubernetes:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh-data:/root/.ssh
    command: 'bash -c "/setup-ssh.sh; /start.sh; while true; do generate_all_deployments; paasta_list_kubernetes_service_instances|shuf|xargs setup_kubernetes_job -v; sleep 2; done"'
    depends_on:
      - paasta_api
      - itest_xenial
      - registry
      - git
    networks:
      - default
      - kubeadm-dind-net
  playground:
    build:
      context: ../
      dockerfile: ./yelp_package/dockerfiles/playground/Dockerfile
    volumes:
      - ../:/work:rw
      - ./paasta:/etc/paasta:rw
      - ./docker_registry.json:/etc/paasta/docker_registry.json:rw
      - ./boto:/etc/boto:rw
      - ./example-services-k8s:/nail/etc/services:rw
      - ./kubernetes:/etc/kubernetes:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh-data:/root/.ssh
    command: '/start.sh'
    depends_on:
      - paasta_master
      - paasta_api
      - itest_xenial
      - registry
      - git
  registry:
    image: registry:2
    ports:
      - '5000:5000'
    networks:
      default: {}
      kubeadm-dind-net:
        ipv4_address: 10.192.0.200
  git:
    build: ../yelp_package/dockerfiles/gitremote/
    command: /usr/sbin/sshd -D
    volumes:
      - ssh-data:/root/.ssh
    ports:
      - 22
  paasta_api:
    build:
      context: ../
      dockerfile: ./yelp_package/dockerfiles/itest/api/Dockerfile
    command: bash -c 'pip install -e /work && while true; do pserve /work/paasta_tools/api/development.ini --reload; echo "RESTARTING API..."; sleep 5; done'
    networks:
      - default
      - kubeadm-dind-net
    ports:
      - '5054:5054'
    volumes:
      - ../:/work:rw
      - nail-etc:/nail/etc
      - ./paasta:/etc/paasta:rw
      - ./docker_registry.json:/etc/paasta/docker_registry.json:rw
      - ./kubernetes:/etc/kubernetes:rw
      - ./example-services-k8s:/nail/etc/services:rw
